<?php

return  [
    "arrayTrains" => [
        [
            'agency' => 'Trenitalia',
            'departure_station' => 'Milano Centrale',
            'destination' => 'Roma Termini',
            'departure_time' => '08:30',
            'arrival_time' => '12:45',
            'train_code' => 'FRA05',
            'carriage_number' => 5,
            'on_time' => true,
            'price' => 49.99,
            'is_deleted' => false,
            'departure_date' => '18/05/2024',
        ],
        [
            'agency' => 'Italo',
            'departure_station' => 'Firenze Santa Maria Novella',
            'destination' => 'Napoli Centrale',
            'departure_time' => '09:15',
            'arrival_time' => '13:30',
            'train_code' => 'ITALO456',
            'carriage_number' => 4,
            'on_time' => true,
            'price' => 39.99,
            'is_deleted' => false,
            'departure_date' => '13/05/2024',
        ],
        [
            'agency' => 'Trenord',
            'departure_station' => 'Bergamo',
            'destination' => 'Lecco',
            'departure_time' => '10:00',
            'arrival_time' => '10:45',
            'train_code' => 'TN678',
            'carriage_number' => 2,
            'on_time' => true,
            'price' => 7.50,
            'is_deleted' => false,
            'departure_date' => '13/05/2024',
        ],
        [
            'agency' => 'Frecciarossa',
            'departure_station' => 'Torino Porta Nuova',
            'destination' => 'Venezia Santa Lucia',
            'departure_time' => '14:20',
            'arrival_time' => '17:45',
            'train_code' => 'FR1020',
            'carriage_number' => 6,
            'on_time' => true,
            'price' => 69.99,
            'is_deleted' => false,
            'departure_date' => '14/05/2024',
        ],
        [
            'agency' => 'Trenord',
            'departure_station' => 'Como Nord Lago',
            'destination' => 'Saronno',
            'departure_time' => '16:45',
            'arrival_time' => '17:15',
            'train_code' => 'TN345',
            'carriage_number' => 3,
            'on_time' => true,
            'price' => 4.20,
            'is_deleted' => false,
            'departure_date' => '15/05/2024',
        ],
    ]
];
